//! Documents that are projections of machine-readable state, not copies of it.
//!
//! # The defect family this closes
//!
//! Every other guard in `tests/contract` asks whether two artifacts name the same things.
//! None asks whether they *say the same thing about* them — and that gap was open when this
//! file was written. `TOOLS` carried a summary per tool, `README.md` carried a column of prose
//! beside each name, and **three of the five disagreed**: a concept's *assertions* against its
//! *citations*, a merge listing *the question an audit needs* against *with the reason*, and a
//! held neighbourhood that had lost *what a merge loser said*. Each was a paraphrase somebody
//! wrote once, and nothing could tell which was current.
//!
//! Stated generally, it is the shape this session met seven times: **two artifacts claim to
//! describe one fact, and nothing mechanically proves that they still agree.**
//!
//! # Why a projection rather than a stricter comparison
//!
//! A bidirectional check makes drift *detectable*. It still leaves two places to edit and a
//! person to keep them consistent, which is the arrangement that produced the drift. Where the
//! fact is an **enumeration** — verbs, tools, bands, dependencies, statuses — one side can be
//! canonical and the other derived, and then there is nothing to keep in step.
//!
//! This is also the product's own thesis turned on itself. KWB exists so that documentation is
//! a projection of structured knowledge rather than a second manually synchronised reality; a
//! repository building that should not maintain its own capability list twice by hand.
//!
//! XVPE has the precedent: its comparison tables are generated by a tool and never hand-edited.
//!
//! # What is deliberately *not* projected
//!
//! Rationale. Every paragraph around the table below is a person's argument and stays a
//! person's. Only the enumeration is derived — what the tools are, which world each reads, and
//! what each answers, all of which the registry already states.
//!
//! # What is owed, and named so it is not mistaken for done
//!
//! The same shape applies to `kwb help` against the dispatch, the bands table against the
//! workspace, and decision status against the ledger. This file establishes the pattern on one
//! of them; the others are checked bidirectionally today and are not yet projections.

use std::path::Path;

use kwb_contract_tests::Between;
use kwb_contract_tests::Quoted_After;
use kwb_contract_tests::Repository_Root;
use kwb_contract_tests::Workspace_Members;
use kwb_mcp::TOOLS;

/// The marker a generated block sits between, so a reader knows not to edit it.
const OPENS: &str = "<!-- generated from kwb_mcp::TOOLS -->";

/// And where it ends.
const CLOSES: &str = "<!-- end generated -->";

/// The bands table's markers, distinct so two generated blocks cannot be confused for one.
const BANDS_OPEN: &str = "<!-- generated from crate manifests -->";

/// And where that one ends.
const BANDS_CLOSE: &str = "<!-- end generated bands -->";

/// The fewest tools a registry could declare and still be worth projecting.
///
/// Five when this was written. The floor exists because a projection of an empty registry is an
/// empty table, and an empty table matches an empty block -- so without this, the comparison above
/// would pass on a surface that had stopped existing.
const MINIMUM_TOOLS: usize = 5;

/// The tool table, as the registry says it should read.
///
/// Every column is derived, not only the names. The names already agreed while the prose did
/// not, so projecting the identifiers alone would have projected the half that was never wrong.
fn Projected() -> String
{
    use core::fmt::Write as _;

    let mut table = String::from("| Tool | World | Answers |\n|---|---|---|\n");
    for tool in TOOLS
    {
        // `writeln!` rather than `push_str(&format!(..))`: one allocation rather than one per
        // row, which is what the lint is for.
        writeln!(table, "| `{}` | {} | {} |", tool.name, tool.world.Name(), tool.summary)
            .expect("writing into a String cannot fail");
    }

    return table;
}


#[test]
fn Test_The_Readme_Tool_Table_Should_Be_What_The_Registry_Projects()
{
    let readme = std::fs::read_to_string(Repository_Root().join("README.md"))
        .expect("README.md should be readable");

    let projected = Projected();
    let carried = Between(&readme, OPENS, CLOSES).unwrap_or_else(|| {
        panic!(
            "README.md carries no generated block. It should contain, between {OPENS} and \
             {CLOSES}:\n\n{projected}"
        )
    });

    assert_eq!(
        carried.trim(),
        projected.trim(),
        "the README's tool table is not what the registry projects. Replace the block between \
         the markers with:\n\n{projected}"
    );
}

#[test]
fn Test_The_Projection_Should_Actually_Describe_The_Tools()
{
    // A projection of an empty registry is an empty table, and an empty table matches an empty
    // block — so the test above would pass on a surface that had stopped existing. This is the
    // floor that makes a clean result mean something.
    let projected = Projected();

    assert!(
        TOOLS.len() >= MINIMUM_TOOLS,
        "only {} tools were found in the registry, so this projection describes almost nothing",
        TOOLS.len()
    );
    for tool in TOOLS
    {
        assert!(
            projected.contains(tool.name),
            "the projection omits {}, so it is not a projection of the registry",
            tool.name
        );
        assert!(
            projected.contains(tool.summary),
            "the projection omits what {} answers, which is the column that drifted",
            tool.name
        );
    }
}

// ---- KWB-75: the bands table, projected from the manifests ----

/// One crate's row: the band it declares, its name, and what it says it owns.
struct Row
{
    band: String,
    name: String,
    owns: String,
}

/// Where a band sorts, derived from the band itself rather than stored beside it.
///
/// A band is a label and not a number — `1p` is the platform tier beside band 1 — so sorting the
/// strings would put `10` before `1p` before `2`. The order falls out of the label: the leading
/// digits as a number, then the suffix, then the crate name. `1` precedes `1p` because an empty
/// suffix precedes `p`, and `3` precedes `10` because ten is larger than three.
///
/// Derived rather than stored, because a second field carrying the order would be a second thing
/// to keep in step — which is the arrangement this whole file exists to remove.
fn Sorts_At(row: &Row) -> (u32, String, String)
{
    let digits: String = row.band.chars().take_while(char::is_ascii_digit).collect();
    let suffix: String = row.band.chars().skip(digits.len()).collect();

    return (digits.parse().unwrap_or(u32::MAX), suffix, row.name.clone());
}

/// Every crate that declares a band, read from the manifests that declare it.
fn Rows() -> Vec<Row>
{
    let mut rows = Vec::new();
    Collect_Rows(&Repository_Root().join("crates"), &mut rows);
    rows.sort_by_key(Sorts_At);

    return rows;
}

/// Walk for manifests carrying a band.
fn Collect_Rows(directory: &Path, rows: &mut Vec<Row>)
{
    let Ok(entries) = std::fs::read_dir(directory)
    else
    {
        return;
    };

    for entry in entries
    {
        let path = entry.expect("a readable directory entry").path();
        if path.is_dir()
        {
            Collect_Rows(&path, rows);
            continue;
        }
        if let Some(row) = Row_From_Manifest(&path)
        {
            rows.push(row);
        }
    }
}

/// The row a manifest declares, or `None` when the file is not a manifest that declares one.
///
/// A row is three values and a manifest has to state all three before it is one. A crate that
/// declares a bandless manifest is deliberately *not* dropped in silence here:
/// `Test_Every_Crate_Should_Declare_Which_Band_It_Is_In` is what fails for that, and it fails
/// naming the crate, which is the outcome that gets it fixed.
fn Row_From_Manifest(path: &Path) -> Option<Row>
{
    if path.file_name().is_none_or(|name| return name != "Cargo.toml")
    {
        return None;
    }

    let text = std::fs::read_to_string(path).expect("a readable manifest");
    let (Some(name), Some(owns), Some(band)) = (
        Quoted_After(&text, "name = "),
        Quoted_After(&text, "description = "),
        Quoted_After(&text, "band = "),
    )
    else
    {
        return None;
    };

    return Some(Row { band, name, owns });
}

/// The bands table, as the manifests say it should read.
fn Projected_Bands() -> String
{
    use core::fmt::Write as _;

    let mut table = String::from("| Band | Crate | Owns |\n|---|---|---|\n");
    for row in Rows()
    {
        writeln!(table, "| {} | `{}` | {} |", row.band, row.name, row.owns)
            .expect("writing into a String cannot fail");
    }

    return table;
}

#[test]
fn Test_The_Readme_Bands_Table_Should_Be_What_The_Manifests_Project()
{
    let readme = std::fs::read_to_string(Repository_Root().join("README.md"))
        .expect("README.md should be readable");

    let projected = Projected_Bands();
    let carried = Between(&readme, BANDS_OPEN, BANDS_CLOSE).unwrap_or_else(|| {
        panic!(
            "README.md carries no generated bands table. It should contain, between \
             {BANDS_OPEN} and {BANDS_CLOSE}:\n\n{projected}"
        )
    });

    assert_eq!(
        carried.trim(),
        projected.trim(),
        "the README's bands table is not what the manifests project. Replace the block between \
         the markers with:\n\n{projected}"
    );
}

#[test]
fn Test_Every_Crate_Should_Declare_Which_Band_It_Is_In()
{
    // A crate with no band is silently absent from the table, which is the shape of a capability
    // nobody is told about — the defect `KWB-61` and `KWB-65` each found on a different surface.
    // The floor is the workspace's own member count, so a crate joining the workspace without a
    // band fails here rather than disappearing.
    let rows = Rows();
    let members = Workspace_Members();

    let bandless: Vec<&String> = members
        .iter()
        .filter(|member| return !rows.iter().any(|row| return &row.name == *member))
        .collect();

    assert!(
        bandless.is_empty(),
        "these crates are workspace members and declare no band, so the projected table would \
         not mention them at all: {bandless:?}"
    );
}
