//! Documents that are projections of machine-readable state, not copies of it.
//!
//! # The defect family this closes
//!
//! Every other guard in `tests/contract` asks whether two artifacts name the same things.
//! None asks whether they *say the same thing about* them — and that gap was open when this
//! file was written. `TOOLS` carried a summary per tool, `README.md` carried a column of prose
//! beside each name, and **three of the five disagreed**: a concept's *assertions* against its
//! *citations*, a merge listing *the question an audit needs* against *with the reason*, and a
//! held neighbourhood that had lost *what a merge loser said*. Each was a paraphrase somebody
//! wrote once, and nothing could tell which was current.
//!
//! Stated generally, it is the shape this session met seven times: **two artifacts claim to
//! describe one fact, and nothing mechanically proves that they still agree.**
//!
//! # Why a projection rather than a stricter comparison
//!
//! A bidirectional check makes drift *detectable*. It still leaves two places to edit and a
//! person to keep them consistent, which is the arrangement that produced the drift. Where the
//! fact is an **enumeration** — verbs, tools, bands, dependencies, statuses — one side can be
//! canonical and the other derived, and then there is nothing to keep in step.
//!
//! This is also the product's own thesis turned on itself. KWB exists so that documentation is
//! a projection of structured knowledge rather than a second manually synchronised reality; a
//! repository building that should not maintain its own capability list twice by hand.
//!
//! XVPE has the precedent: its comparison tables are generated by a tool and never hand-edited.
//!
//! # What is deliberately *not* projected
//!
//! Rationale. Every paragraph around the table below is a person's argument and stays a
//! person's. Only the enumeration is derived — what the tools are, which world each reads, and
//! what each answers, all of which the registry already states.
//!
//! # What is owed, and named so it is not mistaken for done
//!
//! The same shape applies to `kwb help` against the dispatch, the bands table against the
//! workspace, and decision status against the ledger. This file establishes the pattern on one
//! of them; the others are checked bidirectionally today and are not yet projections.

use std::path::PathBuf;

use kwb_mcp::TOOLS;

/// The repository root, from this test's own manifest.
fn Repository_Root() -> PathBuf
{
    return PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|tests| return tests.parent())
        .expect("tests/contract sits two levels below the root")
        .to_path_buf();
}

/// The marker a generated block sits between, so a reader knows not to edit it.
const OPENS: &str = "<!-- generated from kwb_mcp::TOOLS -->";

/// And where it ends.
const CLOSES: &str = "<!-- end generated -->";

/// The tool table, as the registry says it should read.
///
/// Every column is derived, not only the names. The names already agreed while the prose did
/// not, so projecting the identifiers alone would have projected the half that was never wrong.
fn Projected() -> String
{
    use core::fmt::Write as _;

    let mut table = String::from("| Tool | World | Answers |\n|---|---|---|\n");
    for tool in TOOLS
    {
        // `writeln!` rather than `push_str(&format!(..))`: one allocation rather than one per
        // row, which is what the lint is for.
        writeln!(table, "| `{}` | {} | {} |", tool.name, tool.world.Name(), tool.summary)
            .expect("writing into a String cannot fail");
    }

    return table;
}

/// What the README currently carries between the markers.
fn Carried(readme: &str) -> Option<String>
{
    let after = readme.split_once(OPENS)?.1;
    let (block, _) = after.split_once(CLOSES)?;

    return Some(block.trim().to_owned());
}

#[test]
fn Test_The_Readme_Tool_Table_Should_Be_What_The_Registry_Projects()
{
    let readme = std::fs::read_to_string(Repository_Root().join("README.md"))
        .expect("README.md should be readable");

    let projected = Projected();
    let carried = Carried(&readme).unwrap_or_else(|| {
        panic!(
            "README.md carries no generated block. It should contain, between {OPENS} and \
             {CLOSES}:\n\n{projected}"
        )
    });

    assert_eq!(
        carried.trim(),
        projected.trim(),
        "the README's tool table is not what the registry projects. Replace the block between \
         the markers with:\n\n{projected}"
    );
}

#[test]
fn Test_The_Projection_Should_Actually_Describe_The_Tools()
{
    // A projection of an empty registry is an empty table, and an empty table matches an empty
    // block — so the test above would pass on a surface that had stopped existing. This is the
    // floor that makes a clean result mean something.
    let projected = Projected();

    assert!(
        TOOLS.len() >= 5,
        "only {} tools were found in the registry, so this projection describes almost nothing",
        TOOLS.len()
    );
    for tool in TOOLS
    {
        assert!(
            projected.contains(tool.name),
            "the projection omits {}, so it is not a projection of the registry",
            tool.name
        );
        assert!(
            projected.contains(tool.summary),
            "the projection omits what {} answers, which is the column that drifted",
            tool.name
        );
    }
}
